title: JK Docs
description: A hub for JKGOC Documentation and Resources
theme: just-the-docs

url: https://mothsinflannel.github.io/JK-Docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout